### ISSUE TITLE
Polygon Layer Viewport Change on Filter Set 

### ISSUE THREAD

**Issue by drunkenmyno** [apache-superset/superset-ui-plugins-deckgl#14]
Expected results
When a Filter is set in a Table for a Polygon Layer.

A Filter is set and the Viewport didnt update.

Error happened

Could not fit viewport Error: @math.gl/web-mercator: assertion failed.

because the Coordiantes are Zero then. after

if (formData.autozoom) {
viewport = fitViewport(viewport, {
width,
height,
points: features.flatMap(getPointsFromPolygon)
});
}

Polygon.js

Actual results
Viewport zooms out to stanrdard 6.85236157047845, 31.222656842808707

How to reproduce the bug
Create a GeoJSON Layer with More then 2 Polygons set a Filter on it.
The Viewport did not update to the Polygon

Environment
superset version: latest
python version: 3.6.4
node.js version: 13
npm version: latest
Checklist
Make sure these boxes are checked before submitting your issue - thank you!

[x ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
[ x] I have reproduced the issue with at least the latest released version of superset.
[x ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by drunkenmyno** [comment]
I found the issue that its in computesBoundsfromPoints.js

because the Polygon Array has more then one array and the d3Extent gets calculated wrong then

any idea to fix?

**Comment by anadue** [comment]
Has this issue been looked at? We see something similar.

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://gitub.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: apache/superset#13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
