### ISSUE TITLE
Multi Viewport Problem

### ISSUE THREAD

**Issue by drunkenmyno** [apache-superset/superset-ui-plugins-deckgl#15]
**Describe the bug**
First of all the Multi Layer Chart did not recognize

this.state.viewport if its set after LoadLayers.

The next one is that Table Filtern would not be recognized

simple fix is changing filters in Multi.jsx to extra_filters and it works.

but the other huge problem is the viewport did not update after a filter is set 

**To Reproduce**

do a multi Layer chart with a Scatterplot and Polygon Layer also create a Table with Filtering options.

now Filter on Multi Layer Chart nothing happend.

**Expected behavior**

The Table Filter should work with Multi Layer Chart (Quick Fix see Above)

**Screenshots**

**Environment (please complete the following information):**
 - superset-ui version: latest
 - Node version: `latest
 - npm version: latest

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://gitub.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: apache/superset#13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
