### ISSUE TITLE
Can not build superset-ui-plugins-deckgl after version 0.2.0

### ISSUE THREAD

**Issue by larsmars** [apache-superset/superset-ui-plugins-deckgl#16]
**Describe the bug**
Can not build superset-ui-plugins-deckgl after version 0.2.0

0.2.0: Build success 
0.2.1: Failed
0.2.2: Failed
0.2.3: Failed
0.2.4: Failed
Master: Failed

**To Reproduce**
1. git clone https://github.com/apache-superset/superset-ui-plugins-deckgl.git
2. npm install
3. npm run build

**Expected behavior**
Build success 

**Actual behaviour**
Build failed.
Error: (Master branch)

```
DRIVER Running TypeScript v3.9.2 driver (failed)

packages/superset-ui-legacy-preset-chart-deckgl/src/components/Tooltip.tsx(2,27): error TS2307: Cannot find module 'xss' or its corresponding type declarations.
packages/superset-ui-legacy-preset-chart-deckgl/src/utils/computeBoundsFromPoints.ts(1,36): error TS7016: Could not find a declaration file for module 'd3-array'. 'C:/source/***/***/superset-ui-plugins-deckgl/node_modules/d3-array/dist/d3-array.js' implicitly has an 'any' type.
  Try `npm install @types/d3-array` if it exists or add a new declaration (.d.ts) file containing `declare module 'd3-array';`

Failed to execute pipeline. The following errors have occurred:

Command failed with exit code 1: tsc --build


    at makeError (C:\source\***\***\superset-ui-plugins-deckgl\node_modules\@boost\core\node_modules\execa\lib\error.js:56:11)
    at handlePromise (C:\source\***\***\superset-ui-plugins-deckgl\node_modules\@boost\core\node_modules\execa\index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

nimbus typescript

```

**Environment (please complete the following information):**
 - Node version: 12.16.1
 - npm version: 6.13.4

**Comment by baltom** [comment]
Adding these dependencies to package.json solved this issue
xss - 1.0.8
@types/d3-array - 1.2.7

Seems that these dependencies sometimes comes from package-lock.json, but as that  file is not checked in you will get the above mentioned error

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://gitub.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: apache/superset#13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
