### ISSUE TITLE
Support for H3HexagonLayer

### ISSUE THREAD

**Issue by assaflavi** [apache-superset/superset-ui-plugins-deckgl#29]
**Is your feature request related to a problem? Please describe.**

I have a bunch of geospatial data indexed by [H3](https://h3geo.org/) that I want to visualize. Currently I'm forced to export it into a CSV, and load it into an ephemeral session on https://kepler.gl/demo

**Describe the solution you'd like**

I'd like this plugin to enable SuperSet visualizations using that type of layer, as it is already [supported in deck.gl](https://deck.gl/docs/api-reference/geo-layers/h3-hexagon-layer).

**Describe alternatives you've considered**
I could not find an existing application that can do this.

**Comment by riazarbi** [comment]
Hello,

I also have a need for this. Could the repo maintainers point me in the right direction for building this myself? Then I could submit a PR.

**Comment by riazarbi** [comment]
Hello, is there any way I can help to expedite this?

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://gitub.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: apache/superset#13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
