### ISSUE TITLE
NaN in formatCategoryLabel() in deck.gl Scatterplot

### ISSUE THREAD

**Issue by rlowit** [apache-superset/superset-ui-plugins-deckgl#32]
**Describe the bug**
The property Point Color using a string field as a Dimension results in a Legend with NaN values in deck.gl Scatterplot

**To Reproduce**
1. Build a deck.gl Scatterplot chart
2. Click on Point Color
3. Select 'Original value' and choose a string as dimension
4. See error NaN in Legend

**Expected behavior**
Selecting 'Original value' as Legend format must bypass D3 formatting and print the string Dimension categories as is.

**Environment (please complete the following information):**
 - superset-ui version: [Version: 0.999.0dev]
 
**Additional context**
When 'Original value' is selected, this.props.format = '~g'.  In formatCategoryLabel() only checks if !this.props.format to return unformatted values. 
A workaround, as suggestion, is to change https://github.com/apache-superset/superset-ui-plugins-deckgl/blob/d081d534d3dd33bbc3f3fbc44ac0707aee22f26c/packages/superset-ui-legacy-preset-chart-deckgl/src/components/Legend.jsx#L58 to 
`if (!this.props.format || this.props.format==='~g') {`

**Comment by mona-mk** [comment]
Any hope to get this fixed soon? This is very annoying, I can't find any workarounds. It worked in previous versions, but now:
<img width="273" alt="Screenshot 2021-07-01 at 15 54 15" src="https://user-images.githubusercontent.com/59080347/124127599-98430780-da84-11eb-9a93-dc92d87b29e9.png">

**Comment by S-eb** [comment]
Same issue here. And I agree this is impacting

**Comment by mona-mk** [comment]
This is fixed, but not released yet :( https://github.com/apache/superset/issues/15738

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://gitub.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: apache/superset#13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
