### ISSUE TITLE
Superset Deck.GL Charts Fail to Load After Installation

### ISSUE THREAD

**Issue by DaveThePianoDude** [apache-superset/superset-ui-plugins-deckgl#34]
**Bug Description**
Ran into two issues while installing on two different operating systems: Ubuntu 20 and Mac OSX Catalina.  Yarn appeared to install successfully.  

**To Reproduce**

Install using the following tools versioned as shown:

1. Python3 v. 3.7.10
2. Node v. 14.17.0
3. yarn v. 1.22.10
4. npm v. 7.15.0

Then, 

git clone ...superset-ui && cd superset-ui
yarn install
yarn build

I ran into two errors show in red letters.  One reported that the build was missing antd;

https://www.npmjs.com/package/antd

The second error reported that it was missing react icons:

https://www.npmjs.com/package/react-icons

I installed each of these packages, and then the install completed.  But when I launched the app on port 9001, the charts do not appear on the side menu.

<img width="1335" alt="Screen Shot 2021-06-09 at 3 40 56 PM" src="https://user-images.githubusercontent.com/5167568/121418575-16eece00-c939-11eb-9015-421166654f47.png">

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - superset-ui version: [e.g. v0.5.0]
 - Node version: `node -v`
 - npm version: `npm -v`
 
**Additional context**

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://gitub.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: apache/superset#13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
