### ISSUE TITLE
How to use new Kepler Plugin

### ISSUE THREAD

**Issue by mshuffett** [apache-superset/superset-ui-plugins-deckgl#5]
I saw this PR #2 that added a Kepler plugin, but I am having trouble figuring out how to add it to Superset. Can you possibly point me in the right direction? @mistercrunch @betodealmeida

**Comment by betodealmeida** [comment]
@mshuffett, the Kepler plugin is not packed with Superset, so we're still figuring out a way of registering it optionally. @khtruong is currently working on it.

**Comment by nishantmonu51** [comment]
@khtruong @betodealmeida : Any updates here ? are there any manual steps that one can follow to use kepler within superset

**Comment by Edefritz** [comment]
Seems @khtruong was not active since end of last year. But having kepler.gl in superset would be super nice. +1 for this and also I'd be willing to help if I can. Not sure if this is a good 1st feature though.

**Comment by khtruong** [comment]
Hi all, apologies for the late reply. I am not actively working on it at the moment.

**Comment by bulam** [comment]
Also interested in this. Any guidance on how to use the integration? Is there maybe a hacky way to use it?

**Comment by mistercrunch** [comment]
We've done a lot of work on the plugin framework recently, meaning the Kepler plugin can be retrofitted into this. 

One key element that's important is the fact that deck.gl and Kepler need to be aligned in term of versions of dependencies that they rely on.

**Comment by chintanp** [comment]
Any updates on this? Where would the relevant documentation be for integrating plugins?

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://gitub.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: apache/superset#13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
