### ISSUE TITLE
Offline Tileserver

### ISSUE THREAD

**Issue by erkdursun** [apache-superset/superset-ui-plugins-deckgl#6]
Is there any config to use local tileserver instead of online mapbox?

**Comment by villebro** [comment]
The codebase on this repo has been moved to the main [Apache Superset repo](https://gitub.com/apache/superset), and consequently the repo is in the process of being archived. See the Superset Improvement Proposal for details: apache/superset#13013 . While all currently open issues and PRs will be closed, we encourage you to reopen this issue on the main repo if it is still relevant.
